name: CI/CD

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  coverage:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Run the tests
        run: npm run test -- --coverage

      - name: Upload results to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
          verbose: true

      - name: Run Fossa scan and upload build data
        uses: fossa-contrib/fossa-action@v1
        with:
          fossa-api-key: 724c243ea7d91698c951ce3fbbf929c7

  quality:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Codacy Analysis CLI
        uses: codacy/codacy-analysis-cli-action@2.0.0
        with:
          verbose: true
          project-token: ${{ secrets.CODACY_TOKEN }}
          upload: true
          fail-if-incomplete: true
          allow-network: true